### ISSUE TITLE
cannot specify working directory when fetching directory plugin names

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/ida-settings#11]
see: https://github.com/williballenthin/ida-settings/pull/9/files#diff-ed394b18efd10ea18953360b54e6b716R708

> this won't quite work. this property is meant to be a 'class property', that is, a property available from the class object itself, and not a specific instance. the intent is allow you to be able to query for all plugin names, without knowing any of them (and therefore, being unable to instantiate any IDASettings).

my initial reaction was to be:
> as a temporary fix, until more discussion, i'm going to move the config directory to a keyword parameter to `directory_plugin_names()`. this will allow you to specify the working directory.

however, this doesn't work, because these are properties, which don't accept arguments.

therefore, my thinking is to update these accessors to be methods, rather than properties, that would look like:

```
def get_system_plugin_names(self):
def get_user_plugin_names(self):
def get_directory_plugin_names(self, config_directory=None):
def get_idb_plugin_names(self):
```

any issues?

**Comment by williballenthin** [comment]
cc: @tmr232

**Comment by williballenthin** [comment]
as a demonstration, `test_directory_plugin_names` is currently failing

**Comment by tmr232** [comment]
Seems like a good solution to me. I think that compromising on methods rather than properties is not an unreasonable compromise.
