### ISSUE TITLE
Add a UI

### ISSUE THREAD

**Issue by tmr232** [williballenthin/ida-settings#13]
As nice as it is to have all settings easily stored, it is not too useful without a way to edit them.
In the present situation, every plugin writer needs to create some way of modifying the settings of his own plugin (much like I did with [IPM](https://github.com/tmr232/IDA-Plugin-Manager).)

A far better solution will be a GUI to allow easy viewing and editing of all the settings.

Sadly, this means writing a GUI...

**Comment by williballenthin** [comment]
acknowledged and agreed. i'll take a stab at this in the near future.

**Comment by williballenthin** [comment]
addressed in 7be8f94b861575d6726e73f6cf27cf0a7c5de08c
