### ISSUE TITLE
Consider releasing latest version to PyPI

### ISSUE THREAD

**Issue by edeca** [williballenthin/ida-settings#18]
Trying to develop on the capa master branch, which now depends on ida-settings. This causes an exception:

```
C:\Program Files\IDA Pro 7.5\plugins\capa_plugin_ida.py: string argument without an encoding
  ...
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\site-packages\ida_settings-1.0.1-py3.7.egg\ida_settings\ida_settings.py", line 859, in <module>
    VALUE_1 = bytes("hello")
TypeError: string argument without an encoding
```

The line no longer exists in the master branch of ida-settings, suggesting the port to Python 3 fixed it.

Would it be worth publishing the latest version of ida-settings to PyPI, so this dependency can be correctly installed?

**Comment by williballenthin** [comment]
yup, this is the plan. didn't have a chance on Friday to rerun the test suites and check that things worked on 7.5. glad to hear it did work for you. I'll do a release and then update capa very soon.

**Comment by williballenthin** [comment]
done!
