### ISSUE TITLE
Problem With Permissions

### ISSUE THREAD

**Issue by tmr232** [williballenthin/ida-settings#6]
On Windows, when trying to write to the system-settings using an unprivileged user, you get no error, but the value is not written.

The write attempt should probably raise some error, so that the user knows what happened.

**Comment by williballenthin** [comment]
yes, i think this should also be done. i'll take a look at it.

**Comment by williballenthin** [comment]
`QSettings` doesn't return an error on `setValue`, nor when calling `status()` after `sync()`. So a potential solution is to test if the user has write access by writing a marker value to some place, and testing that the expected value exists afterwards. 

On first pass, I'll put this in `SystemIDASettings.set_value()` and `.del_value()` and cache the result in the instance.

**Comment by tmr232** [comment]
Do you know if this happens in the native API as well, or only in the Python bindings?

**Comment by williballenthin** [comment]
this fix doesn't work yet.

**Comment by williballenthin** [comment]
i'm not sure. the documentation suggests there should be an error returned from `status()` [link](http://doc.qt.io/qt-4.8/qsettings.html#status) but I'm not seeing this from Python.

**Comment by williballenthin** [comment]
in 9a12ef2411a4937321e7271882a7c97089a28339 the permissions checking is extended to the system, user, and directory settings, since all of these may also have the same issue (perhaps unlikely, but better to be explicit).

**Comment by williballenthin** [comment]
in 9a12ef2411a4937321e7271882a7c97089a28339 the permission checking is extended to all classes that use `QSettings` to persist keys and values (that is, system, user, and directory scope).

**Comment by tmr232** [comment]
Well, seems like this is an issue with Qt itself [QTBUG-21062](https://bugreports.qt.io/browse/QTBUG-21062). There's some chatter about it if you bother to look, but no solution.

I guess the permission check is the best solution we have.
